baseURL: 'https://alican.de/'
languageCode: 'en-us'
title: 'Alican Toprak'
theme: "stack"

enableGitInfo: true
### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: 
      - identifier: about
        name: about
        url: /about/
      - identifier: git
        name: git
        url: /git/


    social:
        - identifier: github
          name: GitHub
          url: https://github.com/alican/
          params:
              icon: brand-github

        - identifier: twitter
          name: Twitter
          url: https://twitter.com
          params:
              icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200
params:
    editURL: https://github.com/alican/alican.github.io/tree/master/content/
    article:
            math: true
            toc: true
            readingTime: true
            license:
                enabled: false
                default: Licensed under CC BY-NC-SA 4.0
    footer:
        customText: Hi
    sidebar:
        compact: false
        emoji: 
        subtitle: Software Engineer from Frankfurt
        avatar:
            enabled: true
            src: "img/avater.png"
            local: true
    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true